### ISSUE TITLE
Alfred 3 update

### ISSUE THREAD

**Issue by Chris-Nicol** [NolanChan/iMessageWorkflow#4]
I realize this is probably not going to happen, but would love it if you could update this to Alfred 3.

Thanks,
Chris

**Comment by NolanChan** [comment]
Hi @Chris-Nicol , I've updated the app to Alfred 3. I've changed a small bit of the functionality, let me know if it suits you!

**Comment by Chris-Nicol** [comment]
thanks!! ... works perfectly again!
