### ISSUE TITLE
IMU - database must be updated on power on

### ISSUE THREAD

**Issue by YangVincent** [NolanChan/iMessageWorkflow#6]

**Comment by YangVincent** [comment]
Inconsistent behavior; will update if I can find anything reliable

**Comment by NolanChan** [comment]
Hi Yang, I'm assuming that you're not using the `im` option that uses OSX's built in contacts? (instead using `oldim`?)

**Comment by YangVincent** [comment]
I was using ```im```, actually. There's likely an old download link floating around somewhere and that's probably what I used. I've since updated! (after looking into [this](https://www.alfredforum.com/topic/3507-textmessage-on-imessage-directly-from-alfred/#entry20497))

**Comment by YangVincent** [comment]
I found it @NolanChan - ```im``` only works if the Contacts app is open. If it isn't, an empty string is placed into the TO: field.

**Comment by NolanChan** [comment]
Thanks for bringing this up and submitting a PR. I believe I fixed the issue slightly differently, but as long as it works that's great!
